# Generated by Django 5.0.4 on 2026-04-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Business', 'Business'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Fiction', 'Fiction'), ('Self-Help', 'Self-Help'), ('Science', 'Science'), ('Classic', 'Classic'), ('Science-Fiction', 'Science-Fiction'), ('Drama', 'Drama')], max_length=100),
        ),
    ]
